[Interface]
Address = 10.13.13.2/32
PrivateKey = EH1sMtI+N2d6yB/lMAjTVkwOS2ZPzpWjnIGuDPpvcG8=
DNS = 1.1.1.1
Table = off

[Peer]
PublicKey = +NGZLlRusAi5g6RbIG79292ul8jGKJ/5xSbvcG8WySw=
AllowedIPs = 0.0.0.0/0
Endpoint = wireguard:51820
PersistentKeepalive = 25
